name: Docker Image Latest

on: 
  push:
    paths:
    - 'Watcher/**'
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:Watcher"
        push: true
        tags: felix83000/watcher:latest
        labels: ${{ steps.meta.outputs.labels }}
